In [1]:
import pandas as pd
import numpy as np

In [ ]:
data =

In [2]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [3]:
df = pd.DataFrame(data, columns=columns)

In [4]:
df.head()

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [6]:
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [12]:
df[['Make', 'Model']]

      Make     Model
0   Nissan    Stanza
1  Hyundai    Sonata
2    Lotus     Elise
3      GMC    Acadia
4   Nissan  Frontier

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Make               5 non-null      object
 1   Model              5 non-null      object
 2   Year               5 non-null      int64
 3   Engine HP          4 non-null      float64
 4   Engine Cylinders   5 non-null      int64
 5   Transmission Type  5 non-null      object
 6   Vehicle_Style      5 non-null      object
 7   MSRP               5 non-null      int64
dtypes: float64(1), int64(3), object(4)
memory usage: 452.0+ bytes

In [21]:
df['id'] = range(1, len(df) + 1)
df.head()

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

In [28]:
df.loc[0:1]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2

In [29]:
df.groupby('Make').agg({'MSRP': 'mean'})

            MSRP
Make
GMC      34450.0
Hyundai  27150.0
Lotus    54990.0
Nissan   17170.0

In [30]:
df.groupby(['Make', 'Model']).agg({'MSRP': 'mean'})

                     MSRP
Make    Model
GMC     Acadia    34450.0
Hyundai Sonata    27150.0
Lotus   Elise     54990.0
Nissan  Frontier  32340.0
        Stanza     2000.0

In [49]:
df.groupby(['Transmission Type']).agg({'MSRP': 'mean'})

                           MSRP
Transmission Type
AUTOMATIC          30800.000000
MANUAL             29776.666667

In [32]:
df.pivot_table(values='MSRP', index='Make', columns='Model', aggfunc='mean')

Model     Acadia    Elise  Frontier   Sonata  Stanza
Make
GMC      34450.0      NaN       NaN      NaN     NaN
Hyundai      NaN      NaN       NaN  27150.0     NaN
Lotus        NaN  54990.0       NaN      NaN     NaN
Nissan       NaN      NaN   32340.0      NaN  2000.0

In [33]:
df.pivot_table(values='MSRP', index='Model', columns='Make', aggfunc='mean')

Make          GMC  Hyundai    Lotus   Nissan
Model
Acadia    34450.0      NaN      NaN      NaN
Elise         NaN      NaN  54990.0      NaN
Frontier      NaN      NaN      NaN  32340.0
Sonata        NaN  27150.0      NaN      NaN
Stanza        NaN      NaN      NaN   2000.0

In [36]:
df['Year'] = df['Year'].astype('int')

In [35]:
df.head()

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Make               5 non-null      object
 1   Model              5 non-null      object
 2   Year               5 non-null      int64
 3   Engine HP          4 non-null      float64
 4   Engine Cylinders   5 non-null      int64
 5   Transmission Type  5 non-null      object
 6   Vehicle_Style      5 non-null      object
 7   MSRP               5 non-null      int64
 8   id                 5 non-null      int64
dtypes: float64(1), int64(4), object(4)
memory usage: 492.0+ bytes

In [42]:
df[df['Year'] > 2010]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

In [44]:
df['Model'].str.lower()

0      stanza
1      sonata
2       elise
3      acadia
4    frontier
Name: Model, dtype: object

In [46]:
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
id                   0
dtype: int64

In [47]:
df.describe()

              Year  Engine HP  Engine Cylinders          MSRP        id
count     5.000000    4.00000          5.000000      5.000000  5.000000
mean   2010.400000  202.75000          4.400000  30186.000000  3.000000
std      11.260551   51.29896          0.894427  18985.044904  1.581139
min    1991.000000  138.00000          4.000000   2000.000000  1.000000
25%    2010.000000  180.00000          4.000000  27150.000000  2.000000
50%    2017.000000  206.00000          4.000000  32340.000000  3.000000
75%    2017.000000  228.75000          4.000000  34450.000000  4.000000
max    2017.000000  261.00000          6.000000  54990.000000  5.000000